[project]
name = "flax"
version = "1.1.0"
description = "flax tacit language"
authors = [ { name = "zoomlogo" } ]
license = { text = "MIT" }
requires-python = ">=3.12"
dependencies = [
    "mpmath",
    "more-itertools",
    "colorama",
]

[project.scripts]
flax = "flax.main:main"

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "pyyaml>=6.0.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88
