name: Format & Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Run ruff formatter
      run: uv run ruff format .

    - name: Run ruff linter
      run: uv run ruff check --fix .

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[style] format and lint files with ruff"
