name: Generate .txt, .json and .csv

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: |
        cd docs
        npm install
    - name: Generate
      run: |
        node docs/yaml-to.js
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.12.0
      with:
        commit_message: Generate .csv, .json and .txt
