name: Generate .txt, .json and .csv

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Install dependencies
      run: npm install
      working-directory: docs

    - name: Generate
      run: node yaml-to.js
      working-directory: docs

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Generate .csv, .json and .txt
